config/routes.rb
Rails.application.routes.draw do
   resources :drinks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/drink.rb
class Drink < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
    def index
         # will have template
         @drinks = Drink.all
        
    end

    def show
         # will have template
        
    end

    def new
        # Display for the new record
         # will have template
        @drink = Drink.new
        
    end

    def create
        # save new Record
        # will save and redirect
        @drink = Drink.new(allowed_params)
            if @drink.save
                redirect_to drinks_path
            else
                redender 'new'
            end
        
    end

    def edit
        # Display form for existing record
        # will have template
        @drink = Drink.find(params[:id])

    end


    def update 
        # save changes
        # will save and redirect
         @drink = Drink.find(params[:id])
          if @drink.update(allowed_params)
                redirect_to drinks_path
            else
                redender 'new'
            end
        
    end

    def destroy
          @drink = Drink.find(params[:id])
          @drink.destroy
          redirect_to drinks_path
   
    end


    private 
        def allowed_params
            params.require(:drink).permit(:name, :size)
        end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/views/drinks/edit.html.erb
<%= form_for @drink do |f| %>
    <%= f.label :name %> <br \> | 
    <%= f.text_field :name %> <br \>

    <%= f.label :size %> <br \>
    <%= f.text_field :size %> <br \>
    
    <%= f.submit %>

<% end %>

<br>
<%= link_to 'Back', drinks_path %>

app/views/drinks/index.html.erb
<h1>Data</h1>

<% @drinks.each do |drink| %>
<p>
Name :<%= drink.name %> <%= link_to 'Edit', edit_drink_path(drink) %> | <%= link_to 'Delete', drink, method: :delete %> <br />
Size :<%= drink.size %>
</p>

<% end %>

<%= link_to 'Add', new_drink_path %>

app/views/drinks/new.html.erb
<%= form_for @drink do |f| %>
    <%= f.label :name %> <br \> | 
    <%= f.text_field :name %> <br \>

    <%= f.label :size %> <br \>
    <%= f.text_field :size %> <br \>
    
    <%= f.submit %>

<% end %>

<br>
<%= link_to 'Back', drinks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BasicPath</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>